version: '3.9'

services:
  mysql1:
    image: mysql/mysql-server:8.0
    container_name: db
    # restart: always
    environment:
        MYSQL_DATABASE: products
        MYSQL_USER: iris
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: password
    ports:
         - 3306:3306
    volumes:
        - ./mysql:/var/lib/mysql
        - ./csv:/csv
        - ./init:/docker-entrypoint-initdb.d
    command: --secure-file-priv=""
    networks:
      - docker_net

  myapp:
      environment:
        DATABASE_HOST: mysql1
        DATABASE_USER: iris
        DATABASE_PASSWORD: test
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - 3000:3000
      depends_on:
        - mysql1
      networks:
        - docker_net

networks:
  docker_net:
    driver: bridge